version: "3.3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nome_db
      MYSQL_USER: nome_usuario
      MYSQL_PASSWORD: = senha_usuario
      # tipo de charset, defaultl = latin1
      MYSQL_CHARSET: latin1
      MYSQL_COLLATION: latin1_swedish_ci
    ports:
      - "3306:3306"
    volumes:
      # persite e carrega o banco ao qual vai ser importado
      - db_data:/var/lib/mysql
      - ./sql_dump:/docker-entrypoint-initdb.d
    command:
      # define o tipo ao qual ser? usado na estrutura do banco
      ["--character-set-server=latin1", "--collation-server=latin1_swedish_ci"]
    networks:
      - mynetwork

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    networks:
      - mynetwork
    working_dir: /var/www/html
    entrypoint: ["composer"]

networks:
  mynetwork:

volumes:
  db_data:
